package gui;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import model.Chat;
import model.Mensaje;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.Random;

import static java.lang.StrictMath.random;

/**
 * @author Usuario
 */
public class ChatForm extends javax.swing.JFrame {
    private Chat chat;

    private ComprarForm comprarForm;

    /**
     * Creates new form ChatForm
     */
    public ChatForm() {
        initComponents();
    }

    public ChatForm(Chat chat, ComprarForm comprarForm) {
        this.chat = chat;
        this.comprarForm = comprarForm;
        initComponents();
    }
    public ChatForm(Chat chat) {
        this.chat = chat;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chatList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        dealTextArea = new javax.swing.JTextArea();
        dealButton = new javax.swing.JButton();
        vendedorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(chatList);

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane2.setViewportView(messageTextArea);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        dealTextArea.setColumns(20);
        dealTextArea.setRows(5);
        jScrollPane4.setViewportView(dealTextArea);

        dealButton.setText("Deal");
        dealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealButtonActionPerformed(evt);
            }
        });

        vendedorLabel.setText(chat.getCompra().getProducto().getVendedor().getNombre());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sendButton)
                                        .addComponent(dealButton)
                                        .addComponent(vendedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(vendedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sendButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dealButton))
                                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void sendButtonActionPerformed(ActionEvent evt) {
        String message = messageTextArea.getText();
        chat.sendMessage(message, this.chat.getCompra().getComprador().getNombre(), this.chat.getCompra().getProducto().getVendedor().getNombre());
        messageTextArea.setText("");
        updateMessages();
    }

    private void updateMessages() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Mensaje mensaje : chat.getMensajes()) {
            model.addElement((mensaje.getEmisor().equals(chat.getCompra().getComprador().getNombre()) ? "Tú" : mensaje.getEmisor()) + ": " + mensaje.getTexto());
        }
        chatList.setModel(model);
    }

    private void dealButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String seleccion = dealTextArea.getText();
        if (seleccion == null) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna oferta");
        } else {
            if(chat.getCompra().getProducto().isPrecioNegociado()){
                JOptionPane.showMessageDialog(null, "La negociación ya ha finalizado");
            } else{
                float deal = Float.parseFloat(seleccion);
                chat.sendMessage("Ofrezco " + deal + "€ por el producto que vendes, ¿Aceptas?", this.chat.getCompra().getComprador().getNombre(), this.chat.getCompra().getProducto().getVendedor().getNombre());
                if (deal > (chat.getCompra().getProducto().getPrecioInicial() - chat.getCompra().getProducto().getPrecioInicial() * 0.2)) {
                    Random r = new Random();
                    int random = r.nextInt(3);
                    if (random == 0) {
                        chat.sendMessage("No, no acepto tu oferta", this.chat.getCompra().getProducto().getVendedor().getNombre(), this.chat.getCompra().getComprador().getNombre());
                    } else {
                        chat.sendMessage("Me parece bien, acepto tu oferta", this.chat.getCompra().getProducto().getVendedor().getNombre(), this.chat.getCompra().getComprador().getNombre());
                        chat.getCompra().getProducto().setPrecio(deal);
                        this.comprarForm.updatePrecio();
                    }
                } else{
                    chat.sendMessage("No, no acepto tu oferta", this.chat.getCompra().getProducto().getVendedor().getNombre(), this.chat.getCompra().getComprador().getNombre());
                }
                updateMessages();
                chat.getCompra().getProducto().setPrecioNegociado(true);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JList<String> chatList;
    private javax.swing.JButton dealButton;
    private javax.swing.JTextArea dealTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel vendedorLabel;
    // End of variables declaration
}
