/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import model.Compra;
import model.Compraventa;
import model.Producto;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class CompraventaForm extends javax.swing.JFrame {
    private Compraventa model;
    /**
     * Creates new form CompraventaForm
     */
    public CompraventaForm() {
        initComponents();
    }

    public CompraventaForm(Compraventa model) {
        this.model = model;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productosList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        buscador = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        detallesButton = new javax.swing.JButton();
        favoritosButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        favoritosList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        comprarButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        comprasList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        vercompraButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(productosList);

        buscador.setColumns(20);
        buscador.setRows(5);
        jScrollPane2.setViewportView(buscador);

        jLabel1.setText("Buscador:");

        detallesButton.setText("Detalles");
        detallesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesButtonActionPerformed(evt);
            }
        });

        favoritosButton.setText("Favoritos");
        favoritosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritosButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(favoritosList);

        jLabel2.setText("Favoritos");

        comprarButton.setText("Comprar");
        comprarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarButtonActionPerformed(evt);
            }
        });

        updateCompras();

        jLabel3.setText("Compras");

        vercompraButton.setText("Ver Compra");
        vercompraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vercompraButtonActionPerformed(evt);
            }
        });

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(54, 54, 54)
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(vercompraButton)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(16, 16, 16))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(comprarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(buscarButton)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(favoritosButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(detallesButton)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(comprarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(buscarButton)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(favoritosButton)
                                        .addComponent(detallesButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(vercompraButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void detallesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String selected = productosList.getSelectedValue();
        if(selected != null){
            String producto = selected.split(" - ")[0];
            for(Producto p : this.model.getProductos()){
                if(p.getNombre().equals(producto)){
                    ProductoForm pf = new ProductoForm(p);
                    pf.setVisible(true);
                }
            }
        }
    }

    private void comprarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String selected = productosList.getSelectedValue();
        if(selected != null){
            String producto = selected.split(" - ")[0];
            for(Producto p : this.model.getProductos()){
                if(p.getNombre().equals(producto)){
                    ComprarForm comprarForm = new ComprarForm(this.model, p);
                    comprarForm.setVisible(true);
                    this.setVisible(false);
                }
            }

        }
    }

    private void vercompraButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String selected = comprasList.getSelectedValue();
        if(selected != null){
            String compra = selected.split(" - ")[0];
            for(Compra c : this.model.getCompras()){
                if(c.getProducto().getNombre().equals(compra)){
                    VerCompraForm vcf = new VerCompraForm(c);
                    vcf.setVisible(true);
                }
            }
        }
    }

    private void favoritosButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String selected = productosList.getSelectedValue();
        if (selected != null) {
            String producto = selected.split(" - ")[0];
            for(Producto p : this.model.getProductos()){
                if(p.getNombre().equals(producto)){
                    p.setFavorito(!p.isFavorito());
                }
            }
        }
        updateFavoritos();
    }

    private void updateFavoritos() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Producto p : this.model.getProductos()) {
            if (p.isFavorito()) {
                model.addElement(p.getNombre());
            }
        }
        favoritosList.setModel(model);
    }

    public void updateCompras(){
        jScrollPane4.setViewportView(comprasList);

        String[] compras = new String[model.getCompras().size()];
        for(int i = 0; i < compras.length; i++){
            compras[i] = model.getCompras().get(i).toString();
        }
        updateProductos();
        updateFavoritos();
        comprasList.setListData(compras);
    }

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        updateProductos();
    }

    public void updateProductos(){
        String texto = buscador.getText();
        ArrayList<String> lista = new ArrayList<String>();
        for(Producto p : this.model.getProductos()){
            if(p.getNombre().toLowerCase().contains(texto.toLowerCase())){
                lista.add(p.getNombre() + " - " + p.getPrecio() + "€");
            }
            String[] resultado = new String[lista.size()];
            for(int i = 0; i < lista.size(); i++){
                resultado[i] = lista.get(i);
            }
            productosList.setListData(resultado);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraventaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraventaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraventaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraventaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraventaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextArea buscador;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton comprarButton;
    private javax.swing.JList<String> comprasList;
    private javax.swing.JButton detallesButton;
    private javax.swing.JButton favoritosButton;
    private javax.swing.JList<String> favoritosList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> productosList;
    private javax.swing.JButton vercompraButton;
    // End of variables declaration
}
