/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Compra;
import model.Entrega;
import model.Valoracion;

import javax.swing.*;

import static java.lang.Integer.parseInt;

/**
 * @author Usuario
 */
public class VerCompraForm extends javax.swing.JFrame {

    private Compra compra;

    /**
     * Creates new form VerCompraForm
     */
    public VerCompraForm() {
        initComponents();
    }

    public VerCompraForm(Compra compra) {
        this.compra = compra;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        productoLabel = new javax.swing.JLabel();
        vendedorLabel = new javax.swing.JLabel();
        pagadoLabel = new javax.swing.JLabel();
        enviadoLabel = new javax.swing.JLabel();
        chatButton = new javax.swing.JButton();
        estrellasTextField = new javax.swing.JTextField();
        valorarButton = new javax.swing.JButton();
        enviarTextField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        productoLabel.setText("Producto: " + compra.getProducto().getNombre());

        vendedorLabel.setText("Vendedor: " + compra.getProducto().getVendedor().getNombre());

        pagadoLabel.setText("Pagado: " + (compra.getPagado() ? "Sí" : "No"));

        enviadoLabel.setText("Enviado: " + (compra.getEnviado() ? "Sí" : "No"));

        chatButton.setText("Chat");
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        estrellasTextField.setText("1/5 estrellas");
        estrellasTextField.setToolTipText("");
        estrellasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estrellasTextFieldActionPerformed(evt);
            }
        });

        valorarButton.setText("Valorar");
        valorarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorarButtonActionPerformed(evt);
            }
        });

        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(valorarButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(estrellasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(chatButton)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(pagadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(vendedorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                                                .addComponent(productoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(enviadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(enviarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enviarButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(productoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendedorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pagadoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enviadoLabel)
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chatButton)
                                        .addComponent(enviarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enviarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(estrellasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(valorarButton))
                                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        compra.getProducto().setPrecioNegociado(true);
        ChatForm chat = new ChatForm(compra.getChat());
        chat.setVisible(true);
    }

    private void valorarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String estrellas = estrellasTextField.getText();
        if (estrellas != null) {
            try {
                if (parseInt(estrellas) > 5 || parseInt(estrellas) < 0) {
                    JOptionPane.showMessageDialog(null, "El numero de estrellas debe estar entre 1 y 5");
                } else {
                    compra.getComprador().addValoracion(new Valoracion(parseInt(estrellas), compra.getComprador(), compra.getProducto()));
                    JOptionPane.showMessageDialog(null, "Valoracion realizada");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El numero de estrellas debe ser un numero entre 1 y 5");
            }

        } else {
            JOptionPane.showMessageDialog(null, "El numero de estrellas debe estar entre 1 y 5");
        }

    }

    private void estrellasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (compra.getEnviado()) {
            JOptionPane.showMessageDialog(this, "El producto ya ha sido enviado");
        } else {
            String selected = enviarTextField.getText();
            if (selected != null) {
                enviarTextField.setText("");
                compra.setEntrega(new Entrega(this.compra, selected));
                updateEnviado();
            } else {
                JOptionPane.showMessageDialog(null, "No se ha especificado una dirección de envío");
            }
        }

    }

    private void updateEnviado() {
        if (compra.getEnviado()) {
            enviadoLabel.setText("Enviado: Si");
        } else {
            enviadoLabel.setText("Enviado: No");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCompraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton chatButton;
    private javax.swing.JLabel enviadoLabel;
    private javax.swing.JButton enviarButton;
    private javax.swing.JTextField enviarTextField;
    private javax.swing.JTextField estrellasTextField;
    private javax.swing.JLabel pagadoLabel;
    private javax.swing.JLabel productoLabel;
    private javax.swing.JButton valorarButton;
    private javax.swing.JLabel vendedorLabel;
    // End of variables declaration
}
